<a href="https://colab.research.google.com/github/jonnie763/DATA-690-Data-Structures-and-Algorithms/blob/main/hw_10_rius_jonathan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a sample code of partitioning. Use 5 as k argument.

In [28]:
import numpy as np

x = np.array([7, 2, 3, 1, 6, 5, 4])

np.partition(x, 5)                   # 5 as k argument (only starts sorting at 5)

array([2, 1, 3, 4, 5, 6, 7])

2. Create a sample structure array using following specification:
- name: OrderDate, format: unicode maximum 8 characters
- name: OrderAmount, format: float 8-bytes
- name: OrderNumber, format: integer 4-bytes
- name: OrderName, format: unicode maximum 20 characters

In [29]:
data = np.zeros(10, dtype={'names':('OrderDate', 'OrderAmount', 'OrderNumber','OrderName'), # OrderDate, OrderAmount, etc..
                          'formats':('U8', 'f8', 'i4','<U20')})                            # Appropriate Format (integers,float, max characters)
print(data.dtype)

[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')]


3. Using #2, create a NumPy array of 10 elements with proper initialization of the structured array. Note order numbers must be between 101 - 110.

In [30]:
OrderDate = ['5/12', '3/12', '3/13', '3/4','5/4','3/4','4/5','4/3','3/2','4/3'] # Ten elements per category 
OrderAmount = [25, 45, 37, 19,12,12,12,21,32,21]
OrderNumber = [101,102,103,104,105,106,107,108,109,110] # Needs to be 101 to 110
OrderName= ['Jon', 'Jonathan', 'Jonny', 'John','J','Jonhny','Jesse','Santiago','Richard','Zaira']

In [31]:
data = np.zeros(10, dtype={'names':('OrderDate', 'OrderAmount', 'OrderNumber','OrderName'), # From previous code
                          'formats':('U8', 'f8', 'i4','<U20')})
print(data.dtype)

[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')]


In [32]:
data['OrderDate'] = OrderDate     # Creating Structured Array 
data['OrderAmount'] = OrderAmount
data['OrderNumber'] = OrderNumber
data['OrderName'] = OrderName
print(data)

[('5/12', 25., 101, 'Jon') ('3/12', 45., 102, 'Jonathan')
 ('3/13', 37., 103, 'Jonny') ('3/4', 19., 104, 'John')
 ('5/4', 12., 105, 'J') ('3/4', 12., 106, 'Jonhny')
 ('4/5', 12., 107, 'Jesse') ('4/3', 21., 108, 'Santiago')
 ('3/2', 32., 109, 'Richard') ('4/3', 21., 110, 'Zaira')]


4. Using the array in #3, filter the array to return orders with order number less than 105. 

In [33]:
data[data['OrderNumber'] < 105]['OrderName'] # Less than 105, but code below has more data and fulfills the requirements 

array(['Jon', 'Jonathan', 'Jonny', 'John'], dtype='<U20')

In [34]:
data[:4] # Simple way to do less than 105

array([('5/12', 25., 101, 'Jon'), ('3/12', 45., 102, 'Jonathan'),
       ('3/13', 37., 103, 'Jonny'), ('3/4', 19., 104, 'John')],
      dtype=[('OrderDate', '<U8'), ('OrderAmount', '<f8'), ('OrderNumber', '<i4'), ('OrderName', '<U20')])

5. Using the code snippet below, fill-in the cell to generate the array as shown at the bottom. 
- You will need to use fancy indexing and masking. 
- Select rows with indices 0, 3, 4, 6, 7
- Use column masking to return every other columns. The first column will be returned, 2nd column will not and so on. 

In [35]:
import numpy as np

rng = np.random.RandomState(0)
x = rng.randint(10, size=(10, 10))

In [36]:
x

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [37]:
 New_Cols=x[:,0::2] # Index every other row
 New_Cols

array([[5, 3, 7, 3, 2],
       [7, 8, 1, 7, 8],
       [5, 8, 4, 0, 5],
       [2, 8, 3, 3, 0],
       [9, 0, 7, 2, 2],
       [0, 5, 6, 4, 4],
       [8, 1, 9, 3, 7],
       [0, 5, 4, 6, 4],
       [4, 8, 3, 5, 0],
       [5, 3, 5, 1, 4]])

In [38]:
row_idx = np.array([0, 3, 4,6,7]) # Index with new variable, using this code for the rows
New_Cols[row_idx[:, None]]

array([[[5, 3, 7, 3, 2]],

       [[2, 8, 3, 3, 0]],

       [[9, 0, 7, 2, 2]],

       [[8, 1, 9, 3, 7]],

       [[0, 5, 4, 6, 4]]])

In [39]:
# Provide your answer here. This is a identical array of the output from the assignment intially. 